---
galaxy_info:
  author: zuritat
  description: "Manages network access and host boundaries. Configures Firewalld zones, hardens SSHD, and sets up Postfix alerts."
  company: Smithsonian Institution
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "9"
        - "10"

dependencies:
  - role: si_foundation
