---
- name: Restart splunk
  ansible.builtin.service:
    name: SplunkForwarder
    state: restarted

- name: Reload Audit Rules
  ansible.builtin.command: /sbin/augenrules --load
  changed_when: true

- name: Restart Auditd Service
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart clamd
  ansible.builtin.service:
    name: clamd@scan
    state: restarted
