---
galaxy_info:
  author: zuritat
  description: Foundation layer (Repos, NTP, Base Packages) for Smithsonian RHEL 9/10
  company: Smithsonian Institution
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "9"
        - "10"

dependencies: []
